# Generated by Django 3.2.2 on 2021-05-09 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('forename', models.CharField(max_length=256)),
                ('lastname', models.CharField(max_length=256)),
                ('avatar', models.CharField(blank=True, max_length=256, null=True)),
                ('birthname', models.CharField(blank=True, max_length=256, null=True)),
                ('birthdate', models.DateTimeField(blank=True, null=True)),
                ('dayOfDeath', models.DateTimeField(blank=True, null=True)),
                ('bio', models.TextField()),
                ('children', models.ManyToManyField(related_name='_api_person_children_+', to='api.Person')),
                ('marriages', models.ManyToManyField(related_name='_api_person_marriages_+', to='api.Person')),
                ('parents', models.ManyToManyField(related_name='_api_person_parents_+', to='api.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=256)),
                ('desciption', models.TextField()),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.person')),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('desciption', models.TextField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.person')),
            ],
        ),
    ]
